-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text NOT NULL CHECK (type = ANY (ARRAY['property'::text, 'user'::text, 'settings'::text, 'system'::text])),
  action text NOT NULL,
  details text,
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'error'::text, 'pending'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.asokore_mampong (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text,
  geometry jsonb,
  properties jsonb,
  status character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real DEFAULT '0'::real,
  paidAmount real DEFAULT '0'::real,
  remainingAmount real DEFAULT '0'::real,
  remarks text,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  CONSTRAINT asokore_mampong_pkey PRIMARY KEY (id)
);
CREATE TABLE public.asokore_mampong_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT asokore_mampong_interests_pkey PRIMARY KEY (id),
  CONSTRAINT asokore_mampong_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.saadi(id),
  CONSTRAINT asokore_mampong_interests_plotId_fkey1 FOREIGN KEY (plotId) REFERENCES public.asokore_mampong(id)
);
CREATE TABLE public.berekuso (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  geometry jsonb,
  properties jsonb,
  status character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real,
  paidAmount real,
  remarks json,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  type character varying,
  remainingAmount integer,
  CONSTRAINT berekuso_pkey PRIMARY KEY (id)
);
CREATE TABLE public.berekuso_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT berekuso_interests_pkey PRIMARY KEY (id),
  CONSTRAINT berekuso_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.berekuso(id)
);
CREATE TABLE public.dar_es_salaam (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text,
  geometry jsonb,
  properties jsonb,
  status character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real,
  paidAmount real,
  remainingAmount real,
  remarks text,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  CONSTRAINT dar_es_salaam_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dar_es_salaam_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT dar_es_salaam_interests_pkey PRIMARY KEY (id),
  CONSTRAINT dar_es_salaam_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.dar_es_salaam(id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL,
  property_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.houseListingImages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  url character varying,
  listing_id uuid,
  CONSTRAINT houseListingImages_pkey PRIMARY KEY (id),
  CONSTRAINT houseListingImages_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.houselistings(id)
);
CREATE TABLE public.houselistings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  address character varying,
  coordinates json,
  createdBy character varying,
  active boolean DEFAULT false,
  propertyType character varying,
  bedroom numeric,
  parking numeric,
  phone real,
  areaSize real,
  price real,
  description text,
  title text,
  type character varying,
  bathroom character varying,
  username character varying NOT NULL,
  fullName character varying,
  CONSTRAINT houselistings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.landListingImages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  url character varying,
  listing_id uuid,
  CONSTRAINT landListingImages_pkey PRIMARY KEY (id),
  CONSTRAINT landListingImages_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.landlistings(id)
);
CREATE TABLE public.landlistings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  address character varying,
  coordinates json,
  active boolean DEFAULT false,
  title character varying,
  price real,
  areaSize real,
  createdBy character varying,
  description text,
  phone character varying,
  username character varying,
  fullName character varying,
  propertyType character varying,
  CONSTRAINT landlistings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legon_hills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  geometry jsonb,
  properties jsonb,
  status character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real,
  paidAmount real,
  remarks json,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  type character varying,
  remainingAmount integer,
  CONSTRAINT legon_hills_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legon_hills_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT legon_hills_interests_pkey PRIMARY KEY (id),
  CONSTRAINT legon_hills_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.legon_hills(id)
);
CREATE TABLE public.news_letter_mails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  email character varying,
  CONSTRAINT news_letter_mails_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text,
  type text NOT NULL,
  property_id uuid,
  details text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.nthc (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text,
  geometry jsonb,
  properties jsonb,
  status character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real DEFAULT '0'::real,
  paidAmount real DEFAULT '0'::real,
  remainingAmount real DEFAULT '0'::real,
  remarks text,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  CONSTRAINT nthc_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nthc_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT nthc_interests_pkey PRIMARY KEY (id),
  CONSTRAINT nthc_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.yabi(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  type text NOT NULL,
  price numeric,
  negotiable boolean DEFAULT false,
  location text NOT NULL,
  address text NOT NULL,
  location_coordinates USER-DEFINED,
  size text NOT NULL,
  bedrooms integer,
  bathrooms integer,
  features jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'sold'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_email text,
  region text,
  rejection_reason text,
  documents json,
  contact numeric,
  property_type character varying NOT NULL DEFAULT 'sale'::character varying,
  rental_type character varying,
  rental_duration character varying,
  rental_price numeric,
  rental_available_from date,
  rental_available_to date,
  rental_deposit numeric,
  rental_utilities_included boolean DEFAULT false,
  rental_furnished boolean DEFAULT false,
  airbnb_min_stay numeric,
  listing_type text,
  CONSTRAINT properties_pkey PRIMARY KEY (id)
);
CREATE TABLE public.property_inquiries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  property_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  message text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'contacted'::text, 'completed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT property_inquiries_pkey PRIMARY KEY (id),
  CONSTRAINT property_inquiries_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.saadi (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text,
  geometry jsonb,
  properties jsonb,
  status character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real DEFAULT '0'::real,
  paidAmount real DEFAULT '0'::real,
  remainingAmount real DEFAULT '0'::real,
  remarks text,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  CONSTRAINT saadi_pkey PRIMARY KEY (id)
);
CREATE TABLE public.saadi_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT saadi_interests_pkey PRIMARY KEY (id),
  CONSTRAINT saad_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.saadi(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.trabuom (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text,
  geometry jsonb,
  properties jsonb,
  status character varying NOT NULL DEFAULT 'Available'::character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real NOT NULL DEFAULT '25000'::real,
  paidAmount real DEFAULT '0'::real,
  remainingAmount real DEFAULT '0'::real,
  remarks text,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  created_at timestamp with time zone DEFAULT now(),
  owner_info text,
  CONSTRAINT trabuom_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trabuom_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT trabuom_interests_pkey PRIMARY KEY (id),
  CONSTRAINT trabuom_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.trabuom(id)
);
CREATE TABLE public.yabi (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text,
  geometry jsonb,
  properties jsonb,
  status character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  country character varying,
  phone character varying,
  residentialAddress character varying,
  agent character varying,
  plotTotalAmount real DEFAULT '0'::real,
  paidAmount real DEFAULT '0'::real,
  remainingAmount real DEFAULT '0'::real,
  remarks text,
  paymentDetails json,
  paymentId character varying,
  paymentReference character varying,
  CONSTRAINT yabi_pkey PRIMARY KEY (id)
);
CREATE TABLE public.yabi_interests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL,
  country text,
  phone text NOT NULL,
  plotId uuid,
  plot_number text NOT NULL,
  plot_name text,
  message text,
  plot_amount text,
  CONSTRAINT yabi_interests_pkey PRIMARY KEY (id),
  CONSTRAINT yabi_interests_plotId_fkey FOREIGN KEY (plotId) REFERENCES public.yabi(id)
);
