export const data = [
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    plotDetails: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
  {
    id: 1,
    title: "Task 1",
    description: "This is the first task",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is the second task",
    status: "Completed",
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is the third task",
    status: "Pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is the fourth task",
    status: "In Progress",
  },
]
